import base64
from urllib.parse import urlsplit
from render_block import render_block_to_string
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, QueryDict
from django.urls import resolve


# The list of htmx attributes that HxResponse recognises, and their header equivalent (for telling htmx to do something different when it receives the response). kwarg is the kwarg name used when creating a HxResponse directly
hx_attributes = [
	# These attributes are native htmx ones. They don't come in request.hx.general - because htmx will process them by default. We only need to process them in request.hx.success/error situations.
	{ 'request': 'location', 'response': 'HX-Location', 'kwarg': 'location'},
	{ 'request': 'push-url', 'response': 'HX-Push-Url', 'kwarg': 'push_url'}, #core
	{ 'request': 'redirect', 'response': 'HX-Redirect', 'kwarg': 'redirect'},
	{ 'request': 'refresh', 'response': 'HX-Refresh', 'kwarg': 'refresh'},
	{ 'request': 'replace-url', 'response': 'HX-Replace-Url', 'kwarg': 'replace_url'}, #core
	{ 'request': 'swap', 'response': 'HX-Reswap', 'kwarg': 'swap'}, #core
	{ 'request': 'target', 'response': 'HX-Retarget', 'kwarg': 'target'}, #core

	# These attributes are pure okayjack ones - we need to process them for all of request.hx.*
	{ 'request': 'fire', 'response': 'HX-Trigger', 'kwarg': 'fire'},
	{ 'request': 'fire-after-receive', 'response': 'HX-Trigger', 'kwarg': 'fire_after_receive'},
	{ 'request': 'fire-after-settle', 'response': 'HX-Trigger-After-Settle', 'kwarg': 'fire_after_settle'},
	{ 'request': 'fire-after-swap', 'response': 'HX-Trigger-After-Swap', 'kwarg': 'fire_after_swap'},
	{ 'request': 'alert', 'response': 'HX-Alert', 'kwarg': 'alert'},
	{ 'request': 'alert-noswap', 'response': 'HX-Alert-Noswap', 'kwarg': 'alert_noswap'},

	# There is also the "do_nothing", "partial", and "block" attributes, but we process them in special ways. (They don't do htmx overrides like the above attributes do)
]

class HxAlert(HttpResponse):
	'''A HttpResponse that tells htmx to execute window.alert - and do nothing else.
	alert_text is encoded so it can include new line characters and be passed using an http header.'''
	def __init__(self, alert_text:str, *args, **kwargs):

		# This class doesn't need the request object unlike the other classes.
		# This might trip people up so we just silently do what they were trying to do in the first place
		if isinstance(alert_text, HttpRequest):
			alert_text = args[0]

		super().__init__(*args, **kwargs)
		self['HX-Alert'] = base64.b64encode(alert_text.encode("utf-8")).decode("ascii")
		self['HX-Reswap'] = 'none'
	status_code = 200

class HxErrorAlert(HxAlert):
	'''422 variant of HxAlert'''
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
	status_code = 422


class HxDoNothing(HttpResponse):
	'''A HttpResponse that tells htmx to do nothing'''
	status_code = 204 # No content


class HxRedirect(HttpResponseRedirect):
	'''A HttpResponse that tells htmx to do a client side redirect to the provided URL
	E.g. HxRedirect(reverse('home'))
	'''
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self['HX-Redirect'] = self['Location']
	status_code = 200


class HxRefresh(HttpResponse):
	'''Refreshes the client.

	There's two types of refreshes:
		1. A standard refresh where the htmx issues an additional request to the url the client is currently on. Standard htmx behaviour when `HX-Refresh=true` is included in the response.
		2. A non-standard refresh where a full page of html (including a body element) is returned in the HttpResponse. htmx then replaces the DOM body with this html. So the client is refreshed without an additional request and without a page flicker 🥳.
	
	Examples:

	# Standard refresh
		HxRefresh()

	# Body swap refresh
		HxRefresh(request, reverse('add_client', args=[client.id]))
	'''
	def __init__(self, request=None, path=None, status_code=None):
		# NOTE: This code is similar to HxResponse. Keep them in sync where possible.

		# We do a response body swap if a path is provided
		if path:
			request.method = 'GET' # If the view handles multiple request methods, we want to use the GET (idempotent) one
			
			url = urlsplit(path)
			resolver = resolve(url.path) # resolve doesn't like querystrings
			request.GET = QueryDict(url.query)
			view_response = resolver.func(request, *resolver.args, **resolver.kwargs)

			# Render if it's a lazy response (TemplateResponse, etc.)
			if hasattr(view_response, 'render'):
				view_response.render()

			# If no status_code provided, use the one from view_response
			if not status_code:
				status_code = view_response.status_code

			# Base HttpResponse on the response generated by the view
			super().__init__(
				content = view_response.content,
				status = status_code,
				content_type = view_response.get('Content-Type', 'text/html'),
			)

			# Ensure a body swap occurs (overriding any previously defined targets or swap styles)
			self['HX-Retarget'] = 'body'
			self['HX-Reswap'] = 'innerHTML'

		# If no path provided, do a normal client side refresh
		else:
			super().__init__()
			self['HX-Refresh'] = "true"


class HxFire(HttpResponse):
	'''A HttpResponse that tells htmx to fire (aka trigger) an event - and do nothing else.
	https://htmx.org/headers/hx-trigger/
	
	Parameters
		fire: the name of the event to fire. Can also be JSON string, which allows for firing multiple events and/or passing data for the event
		fire_after_receive: same as fire, but after receive
		fire_after_swap: same as fire, but after swap
		fire_after_settle: same as fire, but after settle
	
		Usage
			HxFire('my-event')
			HxFire(fire='my-event')
			HxFire(fire_after_receive='my-event')
			HxFire(fire_after_swap='my-event')
			HxFire(fire_after_settle='my-event')
	'''
	def __init__(self, fire=None, *args, fire_after_receive=None, fire_after_swap=None, fire_after_settle=None, **kwargs):
		super().__init__(*args, **kwargs)

		# Two ways to define HX-Trigger (fire can be a positional or keyword argument)
		if fire:
			self['HX-Trigger'] = fire
		elif fire_after_receive:
			self['HX-Trigger'] = fire_after_receive

		if fire_after_swap:
			self['HX-Trigger-After-Swap'] = fire_after_swap
		if fire_after_swap:
			self['HX-Trigger-After-Settle'] = fire_after_settle

		self['HX-Reswap'] = 'none'


class BlockResponse(HttpResponse):
	'''Creates a TemplateResponse like object using django-render-block to render just a block in a template
	The format of block is "template_name#block_name"
	'''
	def __init__(self, request, block, context, **kwargs):
		template_name, block_name = block.split('#')
		super().__init__(render_block_to_string(template_name=template_name, block_name=block_name, context=context, request=request), **kwargs)


class HxResponse(HttpResponse):
	'''Returns a TemplateResponse-like object with HX headers like HX-Retarget for controlling htmx behaviour.

	The values to return as HX headers can come from: hx-*, hx-success-*, or hx-error-* attributes in the HTML, or kwargs when creating a HxResponse, HxSuccessResponse, or HxErrorResponse in the View.
	
	It is valid for the values to come from a combination of the above sources, so this class determines which one to use based on an order of importance. 
	
	From most important to least:
	1. kwargs
	2. hx-success-* or hx-error-* attributes
	3. hx-* attrributes

	Values of higher importance supercede those of lower importance. The class then returns a response with the most important value for each attribute (target, swap, etc).
	'''

	def __init__(self, request, *args, **kwargs):

		state = kwargs.pop('state', None)
		status = kwargs.pop('status', None)

		# Work out if do_nothing is True or False
		do_nothing = (
			kwargs.pop('do_nothing', None) 
			or (state and 'do-nothing' in request.hx[state]) 
			or ('do-nothing' in request.hx['general'])
		)

		# Get the value of `refresh` if there is one
		refresh = ( 
			kwargs.pop('refresh', None) 
			or (request.hx[state].get('refresh') if state and state in request.hx else None) 
			or request.hx['general'].get('refresh')
		)

		# Processing shortcuts for DoNothing or Refresh. If either of these are present, none of the other hx attributes apply, so these checks allow the HxResponse to return without processing the partial/block etc.

		if do_nothing:
				# Default to status 204 for do-nothing responses
				if status is None or status == 200:
					status = 204
				super().__init__(status=status)
				# We use this special response header to tell the JavaScript to not swap in the response body.
				# Vanilla htmx supports this through returning a 204 status code. We want to support more status codes than just 204 so we do it this way instead. This will allow the request status to be queried in analytics programs (e.g. django-silent-mammoth-whistle)
				self['HX-Do-Nothing'] = 'true'
		
		elif refresh :
				if refresh == True or refresh.lower() == 'true':
					super().__init__(status=status)
					self['HX-Refresh'] = "true"
				else:
					request.method = 'GET' # If the view handles multiple request methods, we want to use the GET (idempotent) one
					
					url = urlsplit(refresh)
					resolver = resolve(url.path) # resolve doesn't like querystrings
					request.GET = QueryDict(url.query)
					view_response = resolver.func(request, *resolver.args, **resolver.kwargs)

					# Render if it's a lazy response (TemplateResponse, etc.)
					if hasattr(view_response, 'render'):
						view_response.render()

					# Base HttpResponse on the response generated by the view
					# Use the status from kwargs though because it may be set to look lik a 4xx response.
					super().__init__(
						content = view_response.content,
						status = status, 
						content_type = view_response.get('Content-Type', 'text/html'),
					)
					self['HX-Retarget'] = 'body'
					self['HX-Reswap'] = 'innerHTML'

		else:
			# We shouldn't actually get HxResponses with no context supplied as there are other classes to cover those edge cases (e.g. HxRefresh), but avoiding that error is best.
			try:
				context = args[0]
				# HttpResponse doesn't take a 'context' argument so we need to remove that before passing the remaining args to super (the HttpResponse __init__ method)
				args = args[1:]
			except IndexError:
				context = None


			# HxSuccessResponse and HxErrorResponse will pass the either a partial or a block reference in kwargs
			# If the user is using hx-partial or hx-block, that will be in request.hx['general']['partial'] or request.hx['general']['block']
			partial = (kwargs.pop('partial', None) or 
				(request.hx[state].get('partial') if state else None) or 
				request.hx['general'].get('partial') or 
				None)
			
			block = (kwargs.pop('block', None) or 
				(request.hx[state].get('block') if state else None) or 
				request.hx['general'].get('block') or 
				None)
			
			# Render HTML from context and partial/block reference (if supplied)
			if partial:
				content_string = render_to_string(template_name=partial, context=context, request=request)
			elif block:
				if '#' in block:
					template_name, block_name = block.split('#')
					content_string = render_block_to_string(template_name=template_name, block_name=block_name, context=context, request=request)
				else:
					content_string = render_to_string(template_name=block, context=context, request=request)
			else:
				# Sometimes we don't want any response body. An empty block (i.e. hx-block="") will end up here as well.
				content_string = ''
			

			# base64 encode alerts that are passed in by kwarg
			# alert text from the client is already base64 encoded - this is just for alert text set in the Django project.
			if 'alert' in kwargs:
				kwargs['alert'] = base64.b64encode(kwargs['alert'].encode("utf-8")).decode("ascii")

			# Pop any special okayjack keyword args so the remaining kwargs can be sent to HttpResponse
			# While we're at it, we determine all the values which should be included in the HttpResponse
			response_values = {}
			for attr in hx_attributes:
				if value := (kwargs.pop(attr['kwarg'], None) 
				 	or (request.hx[state].get(attr['request']) if state else None) 
					or request.hx['general'].get(attr['request'])):
						
						response_values[attr['response']] = value

			# Create HttpResponse
			# We need to do this before setting the headers to there's a response to set the headers on
			#
			# `status` kwarg is used by okayjack as well as HttpResponse. 
			# For okayjack usage, the value is in the request.state object so we need to explicitly include it as a kwarg to HttpResponse here.
			super().__init__(content_string, *args, status=status, **kwargs)

			# The following if statement is to support a programmer convenience / edge case
			# If the request includes an alert, but no block/partial included, and no swap was specified, we assume the programmer intends to only display an alert after the response is processed. 
			# This means they don't have to add a `hx-swap=none` to accompany a `hx-alert`.
			# It's expected this could be common usage for the error path. e.g. programmer is saying, "if there is an error, just display a browser alert and do nothing else"
			if 'HX-Alert' in response_values and content_string == '' and 'HX-Swap' not in response_values:
				self['HX-Reswap'] = 'none'

			# Set response headers
			for key, value in response_values.items():
				self[key] = value


class HxSuccessResponse(HxResponse):
	'''A convenience class for creating a 'sucess' HxResponse. This is just done by adding the state='success' kwarg.'''
	def __init__(self, request, *args, **kwargs):
		super().__init__(request, *args, state='success', status=200, **kwargs)

class HxErrorResponse(HxResponse):
	'''A convenience class for creating an 'error' HxResponse. This is just done by adding the state='error' kwarg.
	
	422 (Unprocessable Content) is the error code we use for generic form submission errors'''
	def __init__(self, request, *args, **kwargs):
		super().__init__(request, *args, state='error', status=422, **kwargs)
